https://www.youtube.com/watch?v=JqQ6MJ9r1r0&list=PLwDQt7s1o9J65aQ6HYN4LaqRkX8ncKG1D&index=78

In [1]:
import numpy as np

# 逻辑斯蒂回归在线性模块下
# 和线性回归类似-------->线性方程
# 逻辑斯蒂回归---------->线性方程
# 不同：
#      线性回归解决回归问题
#      逻辑斯蒂回归解决分类问题

# 所有的分类问题都是概率问题
# 线性方程 ---------->逻辑斯蒂函数------------>概率问题 0 ~ 1 -------------->分类问题
from sklearn.linear_model import LogisticRegression

In [2]:
'''假如有一个罐子，里面有黑白两种颜色的球，数目多少不知，两种颜色的比例也不知。
我 们想知道罐中白球和黑球的比例，但我们不能把罐中的球全部拿出来数。
现在我们可以每次任意从已经摇匀的罐中拿一个球出来，记录球的颜色，然后把拿出来的球 再放回罐中。
这个过程可以重复，我们可以用记录的球的颜色来估计罐中黑白球的比例。假如在前面的一百次重复记录中，有七十次是白球，
请问罐中白球所占的比例最有可能是多少？
很多人马上就有答案了：70%。而其后的理论支撑是什么呢？'''

# 白球是 p，黑球 1-p

#取来一个球，白球概率：p
#取两个球，都是白球概率 ：p**2

#取了一百次，30次黑球，70次白球：p**70*(1-p)**30


# 最大似然
#70*p**69*(1-p)**30 + p**70*30*(1-p)**29*(-1) = 0

#70*(1-p) - p*30 = 0

#70 - 100p = 0

#p = 70%

'假如有一个罐子，里面有黑白两种颜色的球，数目多少不知，两种颜色的比例也不知。\n我 们想知道罐中白球和黑球的比例，但我们不能把罐中的球全部拿出来数。\n现在我们可以每次任意从已经摇匀的罐中拿一个球出来，记录球的颜色，然后把拿出来的球 再放回罐中。\n这个过程可以重复，我们可以用记录的球的颜色来估计罐中黑白球的比例。假如在前面的一百次重复记录中，有七十次是白球，\n请问罐中白球所占的比例最有可能是多少？\n很多人马上就有答案了：70%。而其后的理论支撑是什么呢？'

In [3]:
'''第二方法'''

#70*(1-p)**30 + p*30*(1-p)**29*(-1) = 0
# 方程坐标除以p**69

#70*(1-p)**30 + p*30*(1-p)**29*(-1) = 0

# 方程左右两边同时除以（1-p）**29

#70*(1-p)+ p*30*(-1) = 0

#70 - 100p = 0

#p = 70%

'第二方法'

In [4]:
a = 10**3*10**5*10**6

a

100000000000000

In [10]:
a = np.log10(10**3) + np.log10(10**5) + np.log10(10**6)
a

14.0

In [6]:
np.log10(a)

14.0

In [11]:
import sklearn.datasets as datasets

In [12]:
iris = datasets.load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [13]:
X = iris['data']

y = iris['target']

In [14]:
# 4个属性花萼长宽，花瓣的长宽
X.shape

(150, 4)

In [15]:
from sklearn.model_selection import train_test_split

In [17]:
X_train,X_test,y_train,y_test = train_test_split(X,y) #默認是0.25

In [ ]:
# class_weight
# 两类：类别A（100），类别B（200）
# class_weight = {A:2,B:1}

In [20]:
lg = LogisticRegression()

lg.fit(X_train,y_train)

LogisticRegression()

In [19]:
np.bincount(y_train)

array([36, 40, 36], dtype=int64)

In [21]:
y_ = lg.predict(X_test)


In [22]:
display(y_,y_test)

array([2, 2, 2, 2, 0, 0, 1, 2, 2, 2, 2, 1, 0, 0, 0, 2, 2, 2, 1, 0, 2, 1,
       2, 1, 2, 2, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1])

array([2, 2, 2, 2, 0, 0, 1, 2, 2, 2, 2, 1, 0, 0, 0, 2, 2, 2, 1, 0, 2, 1,
       2, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 2, 0, 0, 1])

In [24]:
lg.score(X_test,y_test) #準確率

0.9210526315789473

In [25]:
lg.predict_proba(X_test) # 誰的概率大選誰

array([[2.45957061e-06, 4.54272208e-03, 9.95454818e-01],
       [1.45625009e-04, 2.89068756e-01, 7.10785619e-01],
       [1.01157534e-03, 4.28218943e-01, 5.70769482e-01],
       [5.51316726e-06, 1.46265990e-02, 9.85367888e-01],
       [9.94799931e-01, 5.20005435e-03, 1.43027252e-08],
       [9.36080488e-01, 6.39190399e-02, 4.71733788e-07],
       [8.79914965e-02, 8.94710130e-01, 1.72983737e-02],
       [2.82491742e-05, 3.84911084e-02, 9.61480642e-01],
       [1.04267181e-03, 2.08429384e-01, 7.90527944e-01],
       [1.70810259e-05, 9.94728523e-02, 9.00510067e-01],
       [2.13991884e-05, 3.87182725e-02, 9.61260328e-01],
       [1.67918339e-02, 9.43535690e-01, 3.96724756e-02],
       [9.78486910e-01, 2.15128737e-02, 2.16207820e-07],
       [9.62327317e-01, 3.76723207e-02, 3.61930666e-07],
       [9.52765852e-01, 4.72337386e-02, 4.09307996e-07],
       [4.91532188e-05, 7.40343034e-02, 9.25916543e-01],
       [1.43263896e-04, 5.15648699e-02, 9.48291866e-01],
       [2.36624376e-05, 1.56392

In [28]:
X_train.shape

(112, 4)

In [26]:
np.bincount(y_train)

array([36, 40, 36], dtype=int64)

In [29]:
lg.coef_

array([[-0.36874058,  0.86182273, -2.29601315, -0.96338016],
       [ 0.47134221, -0.65977723, -0.09468768, -1.01385   ],
       [-0.10260164, -0.2020455 ,  2.39070083,  1.97723016]])

In [30]:
lg.intercept_

array([  8.85282558,   3.02110053, -11.87392611])

In [31]:
cond = y!=2

In [32]:
X = X[cond]

In [33]:
y = y[cond]

In [34]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [36]:
lg.fit(X,y)

LogisticRegression()

In [37]:
lg.coef_

array([[ 0.44036482, -0.90696813,  2.30849566,  0.96232763]])

In [38]:
lg.intercept_

array([-6.61165119])