In [1]:
import numpy as np

from sklearn.linear_model import LinearRegression

import sklearn.datasets as datasets

# 糖尿病

In [2]:

diabetes = datasets.load_diabetes()
diabetes

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990842, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06832974, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286377, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04687948,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452837, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00421986,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59

### SEX 性別 ,BMI 值,BP 血壓, s1-s6 血液內部血清的值

In [6]:
#資料
X = diabetes['data']
#目標值
y = diabetes['target']

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2)

In [9]:
X_train.shape

(353, 10)

In [10]:
X_train[:5]

array([[-0.00188202, -0.04464164, -0.02668438,  0.04941532,  0.05897297,
        -0.01603186, -0.04708248,  0.07120998,  0.13359898,  0.01963284],
       [ 0.06713621,  0.05068012, -0.03638469, -0.08485664, -0.00707277,
         0.01966707, -0.05444576,  0.03430886,  0.0011438 ,  0.03205916],
       [ 0.00538306,  0.05068012, -0.00189471,  0.00810087, -0.00432087,
        -0.01571871, -0.00290283, -0.00259226,  0.03839325, -0.01350402],
       [ 0.00538306,  0.05068012,  0.0347509 , -0.00108012,  0.15253776,
         0.19878799, -0.06180903,  0.18523444,  0.01556684,  0.07348023],
       [ 0.01264814, -0.04464164,  0.03367309,  0.03334859,  0.03007796,
         0.02718263, -0.00290283,  0.00884709,  0.03119299,  0.02791705]])

In [11]:
# 该数据有正有负，说明此数据被处理过，归一化
X_train.std(axis = 0)

array([0.04722989, 0.0475596 , 0.04708042, 0.0477489 , 0.0474701 ,
       0.04719049, 0.04713629, 0.04808754, 0.0484562 , 0.04716373])

In [12]:
lr = LinearRegression()

In [13]:
lr.fit(X_train,y_train)

LinearRegression()

In [14]:
y_ = lr.predict(X_test)
y_.round(2)

array([185.02, 103.36, 239.69, 182.83, 145.48, 105.12,  61.95, 144.81,
       282.74, 168.81, 228.03,  95.98, 201.12, 155.26, 205.67,  78.79,
       256.61, 104.15,  50.15, 134.28, 175.68, 127.13,  78.25, 178.31,
       214.29, 120.22, 248.09,  90.21, 125.84, 118.77, 212.28, 151.51,
       146.65, 121.06, 130.72, 129.34, 123.42, 139.01, 172.47, 172.39,
       226.1 ,  83.38, 165.23,  82.9 , 142.59, 151.23,  56.76,  80.2 ,
       165.1 , 232.87, 219.66, 169.39, 103.62, 177.06, 127.87, 156.11,
       181.61, 148.31,  57.32,  81.74, 109.27, 252.53, 172.95,  77.33,
        99.57, 194.95, 246.4 , 100.73, 160.97, 146.49, 236.03, 248.89,
       144.73, 121.31, 177.44, 217.78,  85.91, 187.74,  92.37, 156.41,
        85.54, 162.18, 156.1 ,  97.91, 122.7 , 123.75, 159.25, 166.14,
        79.33])

In [15]:
y_test

array([170.,  72., 258., 144.,  85.,  47.,  52., 302., 258., 151., 208.,
        54., 151., 172., 288.,  48., 263.,  90.,  55., 187., 180.,  71.,
        77.,  91., 121., 150., 336.,  84., 162.,  53., 275.,  73., 116.,
       144., 148.,  42., 191.,  90.,  85., 140., 155.,  53., 206.,  42.,
       182., 246.,  99.,  89., 127., 275., 332., 235.,  63., 283.,  51.,
       141., 263., 202.,  39.,  51.,  97., 245., 131.,  77., 125., 122.,
       264., 170., 198., 210., 217., 233.,  83., 127.,  77., 192.,  93.,
       232.,  91., 200., 102., 196., 113.,  53., 140., 178., 100., 258.,
        72.])

In [ ]:
'''The coefficient R^2 is defined as (1 - u/v), where u is the residual
sum of squares ((y_true - y_pred) ** 2).sum() and v is the total
sum of squares ((y_true - y_true.mean()) ** 2).sum().
The best possible score is 1.0 and it can be negative (because the
model can be arbitrarily worse). A constant model that always
predicts the expected value of y, disregarding the input features,
would get a R^2 score of 0.0.'''

In [16]:
# R2 决定系数
lr.score(X_test,y_test)

0.5363992310175298

In [19]:
# ((y_true - y_pred) ** 2).sum()
u = ((y_test - y_)**2).sum()
u

250259.19605299953

In [20]:
# ((y_true - y_true.mean()) ** 2).sum()
v = ((y_test - y_test.mean())**2).sum()
v

539816.1797752809

In [21]:
1 - u/v

0.5363992310175298

In [ ]:
#回歸問題 =>矩陣運算

In [ ]:
#如果要求解多個參數時,需要梯度下降(最簡單 比較容易理解的優化方式)

In [ ]:
#線性回歸評價標準:
   #lr.score 算法提供的 可以為負數

In [ ]:
#回歸評量指標:

#https://scikit-learn.org/stable/modules/model_evaluation.html#regression-metrics

In [22]:
#另一種評價標準:
#解釋方差得分
1 - np.var(y_test - y_)/np.var(y_test)

0.5365434150439337

In [23]:
#另一種評價標準:
#平均絕對誤差
np.abs(y_test - y_).mean()

43.21580758600577

In [24]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,mean_squared_log_error

In [25]:
#平均絕對誤差
mean_absolute_error(y_test,y_)

43.21580758600577