In [28]:
# 當數據量比較少的時候，樣本比例一定要相同
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.neighbors import KNeighborsClassifier

In [4]:
data = []
for i in range(10):
    for j in range(1,501):
       data.append(plt.imread('./data_num/%d/%d_%d.bmp'%(i,i,j)))

In [5]:
len(data)

5000

In [6]:
#數據
X = np.array(data)


In [7]:
X.shape #5000張 28x28

(5000, 28, 28)

In [8]:
y = [0,1,2,3,4,5,6,7,8,9]* 500


In [9]:
 y = np.array(y)

In [10]:
y.sort()

In [11]:
# 建模:
     #5000個數據一分為二，4000個訓練數據，1000個測試數據(驗證算法，模型到底好不好)

#隨機抽樣，不影響算法，算法根據距離來進行
    
index = np.random.randint(0,5000,size = 4000)    

X_train = X[index]
Y_train = y[index]

index = np.random.randint(0,5000,size = 1000)  


X_test =  X[index]
Y_test =  y[index]

In [12]:
X_train.shape

(4000, 28, 28)

In [13]:
Y_train.shape

(4000,)

In [14]:
#由於 Y_train是一維 所以X_train也要一維
#sklearn中的訓練數據，必須是二維[[樣本一],[樣本二],[樣本三]]
X_train.reshape(4000,784)

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [15]:
%%time
knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train.reshape(4000,-1),Y_train) #還未計算距離

Wall time: 636 ms


KNeighborsClassifier()

In [16]:
%%time
#預測
y_ = knn.predict(X_test.reshape(1000,784))

Wall time: 5 s


In [17]:
y_[:20]

array([0, 4, 7, 6, 0, 2, 0, 6, 1, 5, 9, 1, 0, 0, 1, 8, 9, 2, 1, 4])

In [18]:
Y_test[:20]

array([0, 4, 7, 6, 0, 2, 0, 6, 1, 5, 9, 1, 0, 0, 1, 8, 9, 2, 1, 4])

In [19]:
(Y_test == y_).mean()

0.94

In [20]:
# 優化　鄰居越多　準確率越少

knn = KNeighborsClassifier(n_neighbors=10)
knn.fit(X_train.reshape(4000,-1),Y_train) #還未計算距離

#predict 計算準確率
knn.score(X_test.reshape(1000,-1),Y_test)

0.924

In [21]:
#

knn = KNeighborsClassifier(n_neighbors=20)

knn.fit(X_train.reshape(4000,-1),Y_train) #還未計算距離

#predict 計算準確率
knn.score(X_test.reshape(1000,-1),Y_test)

0.907

In [22]:
#　透過資料距離來判斷權重

knn = KNeighborsClassifier(n_neighbors=5,weights='distance')

knn.fit(X_train.reshape(4000,-1),Y_train) #還未計算距離

#predict 計算準確率
knn.score(X_test.reshape(1000,-1),Y_test)

0.973

In [24]:
#　透過資料距離來判斷權重 p 

knn = KNeighborsClassifier(n_neighbors=5,weights='distance')

knn.fit(X_train.reshape(4000,-1),Y_train) #還未計算距離

#predict 計算準確率
knn.score(X_test.reshape(1000,-1),Y_test)

0.973

In [30]:
#　透過資料距離來判斷權重  p =2 標準歐肌理德距離

knn = KNeighborsClassifier(n_neighbors=5,weights='distance',p=1)

knn.fit(X_train.reshape(4000,-1),Y_train) #還未計算距離

#predict 計算準確率
knn.score(X_test.reshape(1000,-1),Y_test)

0.971

In [31]:
%%time
#　透過資料距離來判斷權重  p =2 標準歐肌理德距離　ｎ_jobs開啟多進程預算

knn = KNeighborsClassifier(n_neighbors=5,weights='distance',p=1,n_jobs=1)

knn.fit(X_train.reshape(4000,-1),Y_train) #還未計算距離

#predict 計算準確率
knn.score(X_test.reshape(1000,-1),Y_test)

Wall time: 4.78 s


0.971

In [32]:
%%time
#　透過資料距離來判斷權重  p =2 標準歐肌理德距離　ｎ_jobs開啟多進程預算  n_jobs=-1 為用電腦所有的進程來算

knn = KNeighborsClassifier(n_neighbors=5,weights='distance',p=1,n_jobs=-1)

knn.fit(X_train.reshape(4000,-1),Y_train) #還未計算距離

#predict 計算準確率
knn.score(X_test.reshape(1000,-1),Y_test)

Wall time: 1.32 s


0.971